version: "3.9"

services:

 mongo:
  image: mongo
  ports:
   - "27017:27017"
 
 keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
    ports:
      - 8080:8080